version: "3.3"
services:
  file-backup:
    build:
      context: ./src/file-backup
      dockerfile: Dockerfile
    volumes:
      - $LOCAL_DESTINATION:/var/destination
      - $SOURCE:/var/source
    ports:
      - 127.0.0.1:18080:18080
    env_file: .env
  db-backup:
    build:
      context: ./src/${DB}-backup
      dockerfile: Dockerfile
    volumes:
      - $LOCAL_DESTINATION:/var/destination
    ports:
      - 127.0.0.1:18081:18080
    env_file: .env
  file-delete:
    build:
      context: ./src/file-delete
      dockerfile: Dockerfile
    volumes:
      - $LOCAL_DESTINATION:/var/destination
    ports:
      - 127.0.0.1:18082:18080
    env_file: .env